"use client";
import { useEffect, useState } from 'react';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Plus, MoreHorizontal, Trash2, CheckCircle2, XCircle } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

type Assistant = { id: string; name: string };
type Faq = { id: string; question: string; answer?: string | null; status: 'PENDING'|'APPROVED'|'REJECTED'; assistantId?: string | null; autoGenerated: boolean; createdAt: string };

export default function CaptainFaqsPage() {
  const [assistants, setAssistants] = useState<Assistant[]>([]);
  const [filterAssistantId, setFilterAssistantId] = useState<'all' | string>('all');
  const [filterStatus, setFilterStatus] = useState<'ALL'|'PENDING'|'APPROVED'|'REJECTED'>('ALL');
  const [faqs, setFaqs] = useState<Faq[]>([]);
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ question: '', answer: '', assistantId: '' });

  async function loadAssistants() {
    const r = await fetch('/api/admin/ai-integration/assistants', { cache: 'no-store' });
    const j = await r.json();
    setAssistants(j?.assistants || []);
  }

  async function loadFaqs() {
    const qs: string[] = [];
    if (filterAssistantId !== 'all') qs.push(`assistantId=${filterAssistantId}`);
    if (filterStatus !== 'ALL') qs.push(`status=${filterStatus}`);
    const url = '/api/admin/ai-integration/faqs' + (qs.length ? `?${qs.join('&')}` : '');
    const r = await fetch(url, { cache: 'no-store' });
    const j = await r.json();
    setFaqs(j?.faqs || []);
  }

  useEffect(() => { loadAssistants(); }, []);
  useEffect(() => { loadFaqs(); }, [filterAssistantId, filterStatus]);

  async function handleCreate() {
    const payload = {
      question: form.question,
      answer: form.answer || undefined,
      assistantId: form.assistantId || undefined,
      status: 'PENDING',
      autoGenerated: false,
    };
    const r = await fetch('/api/admin/ai-integration/faqs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) });
    if (r.ok) {
      setOpen(false);
      setForm({ question: '', answer: '', assistantId: '' });
      loadFaqs();
    }
  }

  async function updateStatus(id: string, status: 'APPROVED'|'REJECTED') {
    const r = await fetch('/api/admin/ai-integration/faqs', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status }) });
    if (r.ok) loadFaqs();
  }

  async function handleDelete(id: string) {
    const r = await fetch(`/api/admin/ai-integration/faqs?id=${id}`, { method: 'DELETE' });
    if (r.ok) loadFaqs();
  }

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Image src="/captain.png" alt="Capitão" width={48} height={48} />
          <div>
            <h2 className="text-xl font-semibold">FAQs</h2>
            <p className="text-sm text-muted-foreground">Ative FAQs automáticas no assistente para sugerir perguntas; aprove ou crie manualmente.</p>
          </div>
        </div>
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogTrigger asChild>
            <Button size="sm"><Plus className="w-4 h-4 mr-2" /> Criar nova FAQ</Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-2xl w-[96vw] max-h-[85vh]">
            <DialogHeader>
              <DialogTitle>Criar FAQ</DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              <div>
                <label className="text-sm font-medium">Pergunta</label>
                <Input value={form.question} onChange={(e) => setForm({ ...form, question: e.target.value })} placeholder="Qual é a dúvida?" />
              </div>
              <div>
                <label className="text-sm font-medium">Resposta (opcional)</label>
                <Textarea value={form.answer} onChange={(e) => setForm({ ...form, answer: e.target.value })} rows={4} />
              </div>
              <div>
                <label className="text-sm font-medium">Assistente (opcional)</label>
                <select className="w-full border rounded h-9 px-2" value={form.assistantId} onChange={(e) => setForm({ ...form, assistantId: e.target.value })}>
                  <option value="">Todos</option>
                  {assistants.map((a) => (
                    <option key={a.id} value={a.id}>{a.name}</option>
                  ))}
                </select>
              </div>
              <div className="flex justify-end gap-2">
                <Button variant="ghost" onClick={() => setOpen(false)}>Cancelar</Button>
                <Button onClick={handleCreate} disabled={!form.question}>Criar</Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      <div className="flex items-center gap-3">
        <label className="text-sm">Status:</label>
        <select className="border rounded h-9 px-2" value={filterStatus} onChange={(e) => setFilterStatus(e.target.value as any)}>
          <option value="ALL">Todos</option>
          <option value="PENDING">Pendentes</option>
          <option value="APPROVED">Aprovadas</option>
          <option value="REJECTED">Rejeitadas</option>
        </select>
        <label className="text-sm ml-4">Assistente:</label>
        <select className="border rounded h-9 px-2" value={filterAssistantId} onChange={(e) => setFilterAssistantId(e.target.value as any)}>
          <option value="all">Todos</option>
          {assistants.map((a) => (
            <option key={a.id} value={a.id}>{a.name}</option>
          ))}
        </select>
      </div>

      <div className="grid gap-3">
        {faqs.length === 0 ? (
          <div className="text-center py-16 border rounded-md">
            <p className="mb-4 text-lg font-medium">Nenhuma FAQ encontrada</p>
            <p className="text-sm text-muted-foreground mb-6">Ative as FAQs automáticas no assistente para sugestões baseadas nas conversas resolvidas.</p>
            <Button onClick={() => setOpen(true)} size="sm"><Plus className="w-4 h-4 mr-2" /> Criar nova FAQ</Button>
          </div>
        ) : (
          faqs.map((f) => (
            <div key={f.id} className="border rounded-md p-4 flex items-start justify-between">
              <div>
                <h3 className="font-medium">{f.question}</h3>
                {f.answer && <p className="text-sm text-muted-foreground mt-1">{f.answer}</p>}
                <div className="text-xs text-muted-foreground mt-2">{f.status} {f.autoGenerated ? '• sugerida pelo Capitão' : ''}</div>
              </div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="ghost" size="icon"><MoreHorizontal className="w-4 h-4" /></Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  {f.status !== 'APPROVED' && (
                    <DropdownMenuItem onClick={() => updateStatus(f.id, 'APPROVED')}>
                      <CheckCircle2 className="w-4 h-4 mr-2" /> Aprovar
                    </DropdownMenuItem>
                  )}
                  {f.status !== 'REJECTED' && (
                    <DropdownMenuItem onClick={() => updateStatus(f.id, 'REJECTED')}>
                      <XCircle className="w-4 h-4 mr-2" /> Rejeitar
                    </DropdownMenuItem>
                  )}
                  <DropdownMenuItem onClick={() => handleDelete(f.id)} className="text-red-600">
                    <Trash2 className="w-4 h-4 mr-2" /> Excluir
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          ))
        )}
      </div>
    </div>
  );
}


