export const quickReplyIGPayload = {
	session_id: "1002859634954741",
	message: "Falar atendente",
	channel_type: "Channel::Instagram",
	language: "pt_BR",
	context: {
		message: {
			id: 39956,
			content: "Falar atendente",
			account_id: 3,
			inbox_id: 105,
			conversation_id: 2232,
			message_type: "incoming",
			created_at: "2025-09-11T08:12:22.045Z",
			updated_at: "2025-09-11T08:12:22.045Z",
			private: false,
			status: "sent",
			source_id:
				"aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDQ3NDk3Mzc2NjYxOjM0MDI4MjM2Njg0MTcxMDMwMTI0NDI1ODczNzUyMDkyNTU5MjcwNzozMjQyMTU5Nzg0MDU5MTkwMjUzMTk4MTA2ODk1NDc2MzI2NAZDZD",
			content_type: "text",
			content_attributes: {
				in_reply_to_external_id: null,
				quick_reply_payload: "@falar_atendente",
			},
			sender_type: "Contact",
			sender_id: 1885,
			external_source_ids: {},
			additional_attributes: {},
			processed_message_content: "Falar atendente",
			sentiment: {},
		},
		conversation: {
			id: 2232,
			account_id: 3,
			inbox_id: 105,
			status: "pending",
			assignee_id: null,
			created_at: "2025-09-10T14:05:55.189Z",
			updated_at: "2025-09-11T08:12:22.052Z",
			contact_id: 1885,
			display_id: 2022,
			contact_last_seen_at: null,
			agent_last_seen_at: "2025-09-10T17:14:27.707Z",
			additional_attributes: {},
			contact_inbox_id: 2177,
			uuid: "63ca5205-cc4f-44ea-a7c6-defc65624922",
			identifier: null,
			last_activity_at: "2025-09-11T08:12:22.045Z",
			team_id: null,
			campaign_id: null,
			snoozed_until: null,
			custom_attributes: {},
			assignee_last_seen_at: null,
			first_reply_created_at: null,
			priority: null,
			sla_policy_id: null,
			waiting_since: "2025-09-10T14:05:55.189Z",
			cached_label_list: null,
			label_list: [],
		},
		contact: {
			id: 1885,
			name: "Witalo Rocha",
			email: null,
			phone_number: null,
			account_id: 3,
			created_at: "2025-07-25T11:02:03.286Z",
			updated_at: "2025-09-11T08:12:22.178Z",
			additional_attributes: {
				social_profiles: {
					instagram: "witalo_rocha_",
				},
				social_instagram_user_name: "witalo_rocha_",
				social_instagram_follower_count: 1262,
				social_instagram_is_verified_user: false,
				social_instagram_is_business_follow_user: true,
				social_instagram_is_user_follow_business: true,
			},
			identifier: null,
			custom_attributes: {},
			last_activity_at: "2025-09-11T08:12:22.157Z",
			contact_type: "lead",
			middle_name: "",
			last_name: "",
			location: null,
			country_code: null,
			blocked: false,
			label_list: [],
		},
		inbox: {
			id: 105,
			channel_id: 4,
			account_id: 3,
			name: "dra.amandasousadv",
			created_at: "2025-07-25T10:44:53.201Z",
			updated_at: "2025-07-25T10:44:53.201Z",
			channel_type: "Channel::Instagram",
			enable_auto_assignment: true,
			greeting_enabled: false,
			greeting_message: null,
			email_address: null,
			working_hours_enabled: false,
			out_of_office_message: null,
			timezone: "UTC",
			enable_email_collect: true,
			csat_survey_enabled: false,
			allow_messages_after_resolved: true,
			auto_assignment_config: {},
			lock_to_single_conversation: false,
			portal_id: null,
			sender_name_type: "friendly",
			business_name: null,
			allow_agent_to_delete_message: true,
			external_token: null,
			csat_response_visible: false,
			csat_config: {},
		},
		"socialwise-chatwit": {
			whatsapp_identifiers: {
				wamid:
					"aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDQ3NDk3Mzc2NjYxOjM0MDI4MjM2Njg0MTcxMDMwMTI0NDI1ODczNzUyMDkyNTU5MjcwNzozMjQyMTU5Nzg0MDU5MTkwMjUzMTk4MTA2ODk1NDc2MzI2NAZDZD",
				whatsapp_id:
					"aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDQ3NDk3Mzc2NjYxOjM0MDI4MjM2Njg0MTcxMDMwMTI0NDI1ODczNzUyMDkyNTU5MjcwNzozMjQyMTU5Nzg0MDU5MTkwMjUzMTk4MTA2ODk1NDc2MzI2NAZDZD",
				contact_source: "1002859634954741",
			},
			contact_data: {
				id: 1885,
				name: "Witalo Rocha",
				phone_number: null,
				email: null,
				identifier: null,
				custom_attributes: {},
			},
			conversation_data: {
				id: 2232,
				status: "pending",
				assignee_id: null,
				created_at: "2025-09-10T14:05:55Z",
				updated_at: "2025-09-11T08:12:22Z",
			},
			message_data: {
				id: 39956,
				content: "Falar atendente",
				content_type: "text",
				message_type: "incoming",
				created_at: "2025-09-11T08:12:22Z",
				interactive_data: {},
				instagram_data: {
					quick_reply_payload: "@falar_atendente",
					interaction_type: "quick_reply",
				},
			},
			inbox_data: {
				id: 105,
				name: "dra.amandasousadv",
				channel_type: "Channel::Instagram",
			},
			account_data: {
				id: 3,
				name: "DraAmandaSousa",
			},
			metadata: {
				socialwise_active: true,
				is_whatsapp_channel: false,
				payload_version: "2.0",
				timestamp: "2025-09-11T08:12:22Z",
				has_whatsapp_api_key: false,
			},
			whatsapp_api_key: null,
			whatsapp_phone_number_id: null,
			whatsapp_business_id: null,
		},
		wamid:
			"aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDQ3NDk3Mzc2NjYxOjM0MDI4MjM2Njg0MTcxMDMwMTI0NDI1ODczNzUyMDkyNTU5MjcwNzozMjQyMTU5Nzg0MDU5MTkwMjUzMTk4MTA2ODk1NDc2MzI2NAZDZD",
		contact_source: "1002859634954741",
		contact_name: "Witalo Rocha",
		contact_phone: null,
		contact_email: null,
		contact_identifier: null,
		contact_id: 1885,
		conversation_id: 2232,
		conversation_status: "pending",
		conversation_assignee_id: null,
		conversation_created_at: "2025-09-10T14:05:55Z",
		conversation_updated_at: "2025-09-11T08:12:22Z",
		message_id: 39956,
		message_content: "Falar atendente",
		message_type: "incoming",
		message_created_at: "2025-09-11T08:12:22Z",
		message_content_type: "text",
		button_id: null,
		button_title: null,
		list_id: null,
		list_title: null,
		list_description: null,
		interaction_type: "quick_reply",
		postback_payload: null,
		quick_reply_payload: "@falar_atendente",
		inbox_id: 105,
		inbox_name: "dra.amandasousadv",
		channel_type: "Channel::Instagram",
		account_id: 3,
		account_name: "DraAmandaSousa",
		whatsapp_api_key: null,
		phone_number_id: null,
		business_id: null,
		socialwise_active: true,
		is_whatsapp_channel: false,
		has_whatsapp_api_key: false,
		payload_version: "2.0",
		timestamp: "2025-09-11T08:12:22Z",
	},
	metadata: {
		event_name: "message.created",
		conversation_id: 2232,
		message_id: 39956,
		account_id: 3,
		inbox_id: 105,
	},
};
