"""add_casos_oab_e_sync_config

Revision ID: 0231e0ee8ee8
Revises: 581c17f50ab8
Create Date: 2026-03-03 02:20:32.188161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0231e0ee8ee8'
down_revision: Union[str, None] = '581c17f50ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oab_sync_configs',
    sa.Column('oab_numero', sa.String(length=20), nullable=False, comment='Número OAB'),
    sa.Column('oab_uf', sa.String(length=2), nullable=False, comment='UF da OAB'),
    sa.Column('tribunal', sa.String(length=20), nullable=False, comment='Tribunal alvo do scraping'),
    sa.Column('ultimo_sync', sa.DateTime(timezone=True), nullable=True, comment='Data/hora da última sincronização'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: idle | running | error'),
    sa.Column('erro_mensagem', sa.Text(), nullable=True, comment='Mensagem de erro da última sync (se houver)'),
    sa.Column('total_processos', sa.Integer(), nullable=False, comment='Total de processos encontrados na última sync'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'oab_numero', 'oab_uf', name='uq_oab_sync_tenant_oab')
    )
    op.create_index(op.f('ix_oab_sync_configs_oab_numero'), 'oab_sync_configs', ['oab_numero'], unique=False)
    op.create_index(op.f('ix_oab_sync_configs_tenant_id'), 'oab_sync_configs', ['tenant_id'], unique=False)
    op.create_table('casos_oab',
    sa.Column('numero', sa.String(length=25), nullable=False, comment='Número CNJ do processo'),
    sa.Column('classe', sa.String(length=255), nullable=True, comment='Classe processual (ex: MANDADO DE SEGURANÇA)'),
    sa.Column('assunto', sa.String(length=255), nullable=True, comment='Assunto do processo'),
    sa.Column('partes_resumo', sa.String(length=500), nullable=True, comment='Resumo das partes (Fulano X Beltrano)'),
    sa.Column('oab_numero', sa.String(length=20), nullable=False, comment='Número OAB que encontrou este caso'),
    sa.Column('oab_uf', sa.String(length=2), nullable=False, comment='UF da OAB'),
    sa.Column('tribunal', sa.String(length=20), nullable=False, comment='Tribunal fonte do scraping'),
    sa.Column('partes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Partes detalhadas [{polo, nome, papel, oab, documento}]'),
    sa.Column('movimentacoes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Movimentações [{descricao, documento_vinculado, tem_documento}]'),
    sa.Column('documentos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Documentos [{nome, tipo, s3_url, tamanho_bytes}]'),
    sa.Column('ultima_sincronizacao', sa.DateTime(timezone=True), nullable=True, comment='Data/hora da última sincronização bem-sucedida'),
    sa.Column('total_movimentacoes', sa.Integer(), nullable=False, comment='Total de movimentações na última sync'),
    sa.Column('novas_movimentacoes', sa.Integer(), nullable=False, comment='Movimentações novas desde última visualização'),
    sa.Column('total_documentos', sa.Integer(), nullable=False, comment='Total de documentos/anexos'),
    sa.Column('monitoramento_ativo', sa.Boolean(), nullable=False, comment='Se o caso está sendo monitorado ativamente'),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'numero', name='uq_casos_oab_tenant_numero')
    )
    op.create_index(op.f('ix_casos_oab_criado_por'), 'casos_oab', ['criado_por'], unique=False)
    op.create_index(op.f('ix_casos_oab_numero'), 'casos_oab', ['numero'], unique=False)
    op.create_index(op.f('ix_casos_oab_oab_numero'), 'casos_oab', ['oab_numero'], unique=False)
    op.create_index(op.f('ix_casos_oab_tenant_id'), 'casos_oab', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_casos_oab_tenant_id'), table_name='casos_oab')
    op.drop_index(op.f('ix_casos_oab_oab_numero'), table_name='casos_oab')
    op.drop_index(op.f('ix_casos_oab_numero'), table_name='casos_oab')
    op.drop_index(op.f('ix_casos_oab_criado_por'), table_name='casos_oab')
    op.drop_table('casos_oab')
    op.drop_index(op.f('ix_oab_sync_configs_tenant_id'), table_name='oab_sync_configs')
    op.drop_index(op.f('ix_oab_sync_configs_oab_numero'), table_name='oab_sync_configs')
    op.drop_table('oab_sync_configs')
    # ### end Alembic commands ###
