"""add_tipo_documento_pje_descricao_pje

Revision ID: 43d36e5bd5b0
Revises: 68a38600a6bc
Create Date: 2026-03-04 04:57:04.759138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d36e5bd5b0'
down_revision: Union[str, None] = '68a38600a6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peticoes', sa.Column('tipo_documento_pje', sa.String(length=200), nullable=True, comment="Label exato do select PJe (ex: 'Petição intercorrente', 'Contestação')"))
    op.add_column('peticoes', sa.Column('descricao_pje', sa.String(length=500), nullable=True, comment='Descrição livre para o campo Descrição do formulário PJe'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peticoes', 'descricao_pje')
    op.drop_column('peticoes', 'tipo_documento_pje')
    # ### end Alembic commands ###
