"""add_tpu_documentos_table

Revision ID: 569d36915a33
Revises: 43d36e5bd5b0
Create Date: 2026-03-04 07:55:08.865053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569d36915a33'
down_revision: Union[str, None] = '43d36e5bd5b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tpu_documentos',
    sa.Column('codigo', sa.Integer(), nullable=False, comment='Código do tipo de documento no CNJ (cod_item)'),
    sa.Column('nome', sa.Text(), nullable=False, comment='Nome do tipo de documento'),
    sa.Column('cod_item_pai', sa.Integer(), nullable=True, comment='Código do item pai (categoria)'),
    sa.Column('glossario', sa.Text(), nullable=True, comment='Descrição/glossário do tipo de documento'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_tpu_documentos_cod_item_pai'), 'tpu_documentos', ['cod_item_pai'], unique=False)
    op.create_index(op.f('ix_tpu_documentos_codigo'), 'tpu_documentos', ['codigo'], unique=False)
    op.create_index(op.f('ix_tpu_documentos_nome'), 'tpu_documentos', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tpu_documentos_nome'), table_name='tpu_documentos')
    op.drop_index(op.f('ix_tpu_documentos_codigo'), table_name='tpu_documentos')
    op.drop_index(op.f('ix_tpu_documentos_cod_item_pai'), table_name='tpu_documentos')
    op.drop_table('tpu_documentos')
    # ### end Alembic commands ###
