"""add_scrape_jobs_and_sync_progress

Revision ID: 92e1e10bd120
Revises: 0231e0ee8ee8
Create Date: 2026-03-03 07:38:05.098578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92e1e10bd120'
down_revision: Union[str, None] = '0231e0ee8ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_jobs',
    sa.Column('parent_job_id', sa.UUID(), nullable=True, comment='Job pai que criou este job'),
    sa.Column('fase', sa.String(length=20), nullable=False, comment='Fase: listing | detail | document'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: pending | running | completed | failed | blocked'),
    sa.Column('tribunal', sa.String(length=20), nullable=False, comment='Código do tribunal (trf1, trf5, tjce, etc.)'),
    sa.Column('oab_numero', sa.String(length=20), nullable=False, comment='Número OAB sendo buscado'),
    sa.Column('oab_uf', sa.String(length=2), nullable=False, comment='UF da OAB'),
    sa.Column('numero_processo', sa.String(length=25), nullable=True, comment='Número CNJ do processo (preenchido a partir da fase detail)'),
    sa.Column('doc_id', sa.String(length=50), nullable=True, comment='ID do documento no tribunal (fase document)'),
    sa.Column('doc_url', sa.Text(), nullable=True, comment='URL do documento no tribunal (fase document)'),
    sa.Column('tentativas', sa.Integer(), nullable=False, comment='Número de tentativas de execução'),
    sa.Column('max_tentativas', sa.Integer(), nullable=False, comment='Máximo de tentativas antes de marcar como failed'),
    sa.Column('erro_mensagem', sa.Text(), nullable=True, comment='Mensagem de erro da última tentativa'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Dados extras: detail_url, doc_description, etc.'),
    sa.Column('resultado_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Resultado da execução (processos listados, detalhes, s3_url, etc.)'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Quando o job começou a executar'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Quando o job completou (sucesso ou falha final)'),
    sa.Column('sync_config_id', sa.UUID(), nullable=True, comment='Referência à config de sync que originou este pipeline'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_job_id'], ['scrape_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_config_id'], ['oab_sync_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_jobs_numero_processo'), 'scrape_jobs', ['numero_processo'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_oab_numero'), 'scrape_jobs', ['oab_numero'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_parent_job_id'), 'scrape_jobs', ['parent_job_id'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_status'), 'scrape_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_sync_config_id'), 'scrape_jobs', ['sync_config_id'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_tenant_id'), 'scrape_jobs', ['tenant_id'], unique=False)
    op.add_column('oab_sync_configs', sa.Column('progresso_detalhado', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Progresso granular: {fase_atual, tribunal_atual, total_processos, processados, total_docs, docs_baixados, tribunais_status}'))
    op.add_column('oab_sync_configs', sa.Column('tribunais', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Lista de tribunais a sincronizar (auto-detectado pela UF)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oab_sync_configs', 'tribunais')
    op.drop_column('oab_sync_configs', 'progresso_detalhado')
    op.drop_index(op.f('ix_scrape_jobs_tenant_id'), table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_sync_config_id'), table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_status'), table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_parent_job_id'), table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_oab_numero'), table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_numero_processo'), table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    # ### end Alembic commands ###
