-- AlterTable
ALTER TABLE "AiAssistant" ADD COLUMN IF NOT EXISTS "sessionTtlSeconds" INTEGER NOT NULL DEFAULT 86400;
ALTER TABLE "AiAssistant" ADD COLUMN IF NOT EXISTS "sessionTtlDevSeconds" INTEGER NOT NULL DEFAULT 300;
