import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";
import { getPrismaInstance } from "@/lib/connections";

const prisma = getPrismaInstance();

export async function GET(request: NextRequest) {
	const session = await auth();
	if (!session?.user?.id) return NextResponse.json({ error: "Não autenticado" }, { status: 401 });
	const { searchParams } = new URL(request.url);
	const assistantId = searchParams.get("assistantId") || undefined;
	const status = searchParams.get("status") || undefined; // PENDING/APPROVED/REJECTED
	const faqs = await prisma.aiFaq.findMany({
		where: {
			userId: session.user.id,
			isActive: true,
			assistantId: assistantId || undefined,
			status: status ? (status as any) : undefined,
		},
		orderBy: { createdAt: "desc" },
		select: {
			id: true,
			question: true,
			answer: true,
			status: true,
			assistantId: true,
			autoGenerated: true,
			createdAt: true,
		},
	});
	return NextResponse.json({ faqs });
}

export async function POST(request: NextRequest) {
	const session = await auth();
	if (!session?.user?.id) return NextResponse.json({ error: "Não autenticado" }, { status: 401 });
	const body = await request.json().catch(() => ({}));
	const question = (body?.question || "").trim();
	const answer = (body?.answer || "").trim();
	const status = (body?.status || "PENDING").toUpperCase();
	const assistantId = body?.assistantId ? String(body.assistantId) : undefined;
	const autoGenerated = !!body?.autoGenerated;
	if (!question) return NextResponse.json({ error: "Pergunta é obrigatória" }, { status: 400 });
	const created = await prisma.aiFaq.create({
		data: {
			userId: session.user.id,
			assistantId,
			question,
			answer: answer || null,
			status: ["PENDING", "APPROVED", "REJECTED"].includes(status) ? (status as any) : "PENDING",
			autoGenerated,
		},
		select: {
			id: true,
			question: true,
			answer: true,
			status: true,
			assistantId: true,
			autoGenerated: true,
			createdAt: true,
		},
	});
	return NextResponse.json({ faq: created }, { status: 201 });
}

export async function PATCH(request: NextRequest) {
	const session = await auth();
	if (!session?.user?.id) return NextResponse.json({ error: "Não autenticado" }, { status: 401 });
	const body = await request.json().catch(() => ({}));
	const id = String(body?.id || "");
	if (!id) return NextResponse.json({ error: "id obrigatório" }, { status: 400 });
	const update: any = {};
	if (typeof body?.question === "string") update.question = body.question.trim();
	if (typeof body?.answer === "string") update.answer = body.answer.trim();
	if (typeof body?.status === "string") update.status = body.status.toUpperCase() as any;
	const faq = await prisma.aiFaq.update({
		where: { id },
		data: update,
		select: { id: true, question: true, answer: true, status: true },
	});
	return NextResponse.json({ faq });
}

export async function DELETE(request: NextRequest) {
	const session = await auth();
	if (!session?.user?.id) return NextResponse.json({ error: "Não autenticado" }, { status: 401 });
	const { searchParams } = new URL(request.url);
	const id = searchParams.get("id");
	if (!id) return NextResponse.json({ error: "id obrigatório" }, { status: 400 });
	await prisma.aiFaq.update({ where: { id }, data: { isActive: false } });
	return NextResponse.json({ ok: true });
}
