/**
 * app/api/admin/ai-integration/assistants/export/route.ts
 *
 * API de Exportação Completa dos Assistentes IA (Capitão)
 *
 * Funcionalidades:
 * - ✅ Exportação completa de todos os assistentes do usuário
 * - ✅ Inclui documentos, FAQs, prompt versions e configurações
 * - ✅ Inclui dados de inbox associations e A/B tests
 * - ✅ Formato JSON estruturado com metadados completos
 * - ✅ Compressão opcional para grandes volumes
 * - ✅ Auditoria e logging detalhado
 */

import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/auth';
import { getPrismaInstance } from '@/lib/connections';
import { createLogger } from '@/lib/utils/logger';

const prisma = getPrismaInstance();
const logger = createLogger('AI-Assistants-Export');

interface ExportFormat {
  version: string;
  exportedAt: string;
  exportedBy: {
    id: string;
    name: string | null;
    email: string;
  };
  metadata: {
    totalAssistants: number;
    totalDocuments: number;
    totalFaqs: number;
    totalPromptVersions: number;
    totalInboxLinks: number;
    totalABTests: number;
    dataIntegrity: {
      assistantsWithDocuments: number;
      assistantsWithFaqs: number;
      assistantsWithPrompts: number;
      assistantsWithInboxes: number;
    };
  };
  assistants: ExportedAssistant[];
  globalDocuments: ExportedDocument[];
  globalFaqs: ExportedFaq[];
}

interface ExportedAssistant {
  id: string;
  name: string;
  description: string | null;
  productName: string | null;
  generateFaqs: boolean;
  captureMemories: boolean;
  instructions: string | null;
  intentOutputFormat: string;
  model: string;
  // SocialWise Flow optimization settings
  embedipreview: boolean;
  reasoningEffort: string;
  verbosity: string;
  temperature: number | null;
  topP: number | null;
  tempSchema: number;
  tempCopy: number;
  maxOutputTokens: number;
  warmupDeadlineMs: number;
  hardDeadlineMs: number;
  softDeadlineMs: number;
  shortTitleLLM: boolean;
  toolChoice: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  // Related data
  documents: ExportedDocument[];
  faqs: ExportedFaq[];
  promptVersions: ExportedPromptVersion[];
  inboxLinks: ExportedInboxLink[];
  abTests: ExportedABTest[];
}

interface ExportedDocument {
  id: string;
  assistantId: string | null;
  title: string;
  sourceUrl: string | null;
  contentText: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

interface ExportedFaq {
  id: string;
  assistantId: string | null;
  question: string;
  answer: string | null;
  status: string;
  autoGenerated: boolean;
  sourceMessageId: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

interface ExportedPromptVersion {
  id: string;
  assistantId: string;
  name: string;
  version: string;
  promptType: string;
  content: string;
  systemPrompt: string | null;
  temperature: number | null;
  maxTokens: number | null;
  isActive: boolean;
  isDefault: boolean;
  abTestWeight: number;
  createdAt: string;
  updatedAt: string;
  metrics: ExportedPromptMetrics[];
}

interface ExportedPromptMetrics {
  id: string;
  promptVersionId: string;
  date: string;
  totalUsage: number;
  successRate: number;
  averageLatency: number;
  averageScore: number;
  tokenUsage: number;
  errorRate: number;
}

interface ExportedInboxLink {
  id: string;
  assistantId: string;
  inboxDbId: string;
  createdAt: string;
  // Inbox details for reference
  inboxDetails: {
    id: string;
    nome: string;
    inboxId: string;
    channelType: string;
    usuarioChatwitId: string;
  };
}

interface ExportedABTest {
  id: string;
  name: string;
  description: string | null;
  assistantId: string;
  promptVersions: string[];
  trafficSplit: any;
  isActive: boolean;
  startDate: string;
  endDate: string | null;
  winnerVersionId: string | null;
  createdAt: string;
  updatedAt: string;
}

/**
 * GET /api/admin/ai-integration/assistants/export
 * 
 * Exporta todos os assistentes IA do usuário com dados relacionados completos
 */
export async function GET(request: NextRequest) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Usuário não autenticado.' }, { status: 401 });
  }

  try {
    const { searchParams } = new URL(request.url);
    const includeInactive = searchParams.get('includeInactive') === 'true';
    const compress = searchParams.get('compress') === 'true';
    const includeMetrics = searchParams.get('includeMetrics') === 'true';

    logger.info('Iniciando exportação de assistentes IA', {
      userId: session.user.id,
      includeInactive,
      compress,
      includeMetrics
    });

    // Buscar todos os assistentes do usuário
    const assistants = await prisma.aiAssistant.findMany({
      where: {
        userId: session.user.id,
        ...(includeInactive ? {} : { isActive: true })
      },
      include: {
        documents: {
          where: includeInactive ? {} : { isActive: true },
          orderBy: { createdAt: 'desc' }
        },
        faqs: {
          where: includeInactive ? {} : { isActive: true },
          orderBy: { createdAt: 'desc' }
        },
        promptVersions: {
          include: {
            metrics: includeMetrics ? {
              orderBy: { date: 'desc' }
            } : false
          },
          orderBy: { createdAt: 'desc' }
        },
        inboxLinks: {
          include: {
            inbox: {
              select: {
                id: true,
                nome: true,
                inboxId: true,
                channelType: true,
                usuarioChatwitId: true
              }
            }
          }
        },
        abTests: {
          orderBy: { createdAt: 'desc' }
        }
      },
      orderBy: { createdAt: 'desc' }
    });

    // Buscar documentos globais (não associados a assistentes específicos)
    const globalDocuments = await prisma.aiDocument.findMany({
      where: {
        userId: session.user.id,
        assistantId: null,
        ...(includeInactive ? {} : { isActive: true })
      },
      orderBy: { createdAt: 'desc' }
    });

    // Buscar FAQs globais
    const globalFaqs = await prisma.aiFaq.findMany({
      where: {
        userId: session.user.id,
        assistantId: null,
        ...(includeInactive ? {} : { isActive: true })
      },
      orderBy: { createdAt: 'desc' }
    });

    // Processar assistentes e dados relacionados
    const exportedAssistants: ExportedAssistant[] = [];
    let assistantsWithDocuments = 0;
    let assistantsWithFaqs = 0;
    let assistantsWithPrompts = 0;
    let assistantsWithInboxes = 0;
    let totalDocuments = 0;
    let totalFaqs = 0;
    let totalPromptVersions = 0;
    let totalInboxLinks = 0;
    let totalABTests = 0;

    for (const assistant of assistants) {
      // Contar estatísticas
      if (assistant.documents.length > 0) assistantsWithDocuments++;
      if (assistant.faqs.length > 0) assistantsWithFaqs++;
      if (assistant.promptVersions.length > 0) assistantsWithPrompts++;
      if (assistant.inboxLinks.length > 0) assistantsWithInboxes++;
      
      totalDocuments += assistant.documents.length;
      totalFaqs += assistant.faqs.length;
      totalPromptVersions += assistant.promptVersions.length;
      totalInboxLinks += assistant.inboxLinks.length;
      totalABTests += assistant.abTests.length;

      // Processar documentos do assistente
      const documents: ExportedDocument[] = assistant.documents.map(doc => ({
        id: doc.id,
        assistantId: doc.assistantId,
        title: doc.title,
        sourceUrl: doc.sourceUrl,
        contentText: doc.contentText,
        isActive: doc.isActive,
        createdAt: doc.createdAt.toISOString(),
        updatedAt: doc.updatedAt.toISOString()
      }));

      // Processar FAQs do assistente
      const faqs: ExportedFaq[] = assistant.faqs.map(faq => ({
        id: faq.id,
        assistantId: faq.assistantId,
        question: faq.question,
        answer: faq.answer,
        status: faq.status,
        autoGenerated: faq.autoGenerated,
        sourceMessageId: faq.sourceMessageId,
        isActive: faq.isActive,
        createdAt: faq.createdAt.toISOString(),
        updatedAt: faq.updatedAt.toISOString()
      }));

      // Processar prompt versions com métricas
      const promptVersions: ExportedPromptVersion[] = assistant.promptVersions.map(prompt => ({
        id: prompt.id,
        assistantId: prompt.assistantId,
        name: prompt.name,
        version: prompt.version,
        promptType: prompt.promptType,
        content: prompt.content,
        systemPrompt: prompt.systemPrompt,
        temperature: prompt.temperature,
        maxTokens: prompt.maxTokens,
        isActive: prompt.isActive,
        isDefault: prompt.isDefault,
        abTestWeight: prompt.abTestWeight,
        createdAt: prompt.createdAt.toISOString(),
        updatedAt: prompt.updatedAt.toISOString(),
        metrics: includeMetrics && (prompt as any).metrics ? (prompt as any).metrics.map((metric: any) => ({
          id: metric.id,
          promptVersionId: metric.promptVersionId,
          date: metric.date.toISOString(),
          totalUsage: metric.totalUsage,
          successRate: metric.successRate,
          averageLatency: metric.averageLatency,
          averageScore: metric.averageScore,
          tokenUsage: metric.tokenUsage,
          errorRate: metric.errorRate
        })) : []
      }));

      // Processar inbox links
      const inboxLinks: ExportedInboxLink[] = assistant.inboxLinks.map(link => ({
        id: link.id,
        assistantId: link.assistantId,
        inboxDbId: link.inboxDbId,
        createdAt: link.createdAt.toISOString(),
        inboxDetails: {
          id: link.inbox.id,
          nome: link.inbox.nome,
          inboxId: link.inbox.inboxId,
          channelType: link.inbox.channelType,
          usuarioChatwitId: link.inbox.usuarioChatwitId
        }
      }));

      // Processar A/B tests
      const abTests: ExportedABTest[] = assistant.abTests.map(test => ({
        id: test.id,
        name: test.name,
        description: test.description,
        assistantId: test.assistantId,
        promptVersions: test.promptVersions,
        trafficSplit: test.trafficSplit,
        isActive: test.isActive,
        startDate: test.startDate.toISOString(),
        endDate: test.endDate?.toISOString() || null,
        winnerVersionId: test.winnerVersionId,
        createdAt: test.createdAt.toISOString(),
        updatedAt: test.updatedAt.toISOString()
      }));

      exportedAssistants.push({
        id: assistant.id,
        name: assistant.name,
        description: assistant.description,
        productName: assistant.productName,
        generateFaqs: assistant.generateFaqs,
        captureMemories: assistant.captureMemories,
        instructions: assistant.instructions,
        intentOutputFormat: assistant.intentOutputFormat,
        model: assistant.model,
        embedipreview: assistant.embedipreview,
        reasoningEffort: assistant.reasoningEffort,
        verbosity: assistant.verbosity,
        temperature: assistant.temperature,
        topP: assistant.topP,
        tempSchema: assistant.tempSchema,
        tempCopy: assistant.tempCopy,
        maxOutputTokens: assistant.maxOutputTokens,
        warmupDeadlineMs: assistant.warmupDeadlineMs,
        hardDeadlineMs: assistant.hardDeadlineMs,
        softDeadlineMs: assistant.softDeadlineMs,
        shortTitleLLM: assistant.shortTitleLLM,
        toolChoice: assistant.toolChoice,
        isActive: assistant.isActive,
        createdAt: assistant.createdAt.toISOString(),
        updatedAt: assistant.updatedAt.toISOString(),
        documents,
        faqs,
        promptVersions,
        inboxLinks,
        abTests
      });
    }

    // Processar documentos globais
    const exportedGlobalDocuments: ExportedDocument[] = globalDocuments.map(doc => ({
      id: doc.id,
      assistantId: doc.assistantId,
      title: doc.title,
      sourceUrl: doc.sourceUrl,
      contentText: doc.contentText,
      isActive: doc.isActive,
      createdAt: doc.createdAt.toISOString(),
      updatedAt: doc.updatedAt.toISOString()
    }));

    // Processar FAQs globais
    const exportedGlobalFaqs: ExportedFaq[] = globalFaqs.map(faq => ({
      id: faq.id,
      assistantId: faq.assistantId,
      question: faq.question,
      answer: faq.answer,
      status: faq.status,
      autoGenerated: faq.autoGenerated,
      sourceMessageId: faq.sourceMessageId,
      isActive: faq.isActive,
      createdAt: faq.createdAt.toISOString(),
      updatedAt: faq.updatedAt.toISOString()
    }));

    // Incluir documentos/FAQs globais no total
    totalDocuments += exportedGlobalDocuments.length;
    totalFaqs += exportedGlobalFaqs.length;

    // Montar formato de exportação
    const exportData: ExportFormat = {
      version: '1.0.0',
      exportedAt: new Date().toISOString(),
      exportedBy: {
        id: session.user.id,
        name: session.user.name || null,
        email: session.user.email || 'unknown@example.com'
      },
      metadata: {
        totalAssistants: exportedAssistants.length,
        totalDocuments,
        totalFaqs,
        totalPromptVersions,
        totalInboxLinks,
        totalABTests,
        dataIntegrity: {
          assistantsWithDocuments,
          assistantsWithFaqs,
          assistantsWithPrompts,
          assistantsWithInboxes
        }
      },
      assistants: exportedAssistants,
      globalDocuments: exportedGlobalDocuments,
      globalFaqs: exportedGlobalFaqs
    };

    const exportJson = JSON.stringify(exportData, null, compress ? 0 : 2);

    logger.info('Exportação de assistentes concluída', {
      userId: session.user.id,
      totalAssistants: exportedAssistants.length,
      totalDocuments,
      totalFaqs,
      totalPromptVersions,
      sizeBytes: Buffer.byteLength(exportJson, 'utf8')
    });

    // Configurar headers para download
    const filename = `assistants-export-${new Date().toISOString().split('T')[0]}.json`;
    
    return new NextResponse(exportJson, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'X-Export-Version': '1.0.0',
        'X-Total-Assistants': exportedAssistants.length.toString(),
        'X-Total-Documents': totalDocuments.toString(),
        'X-Total-Faqs': totalFaqs.toString(),
        'X-Total-Prompt-Versions': totalPromptVersions.toString(),
        'X-Include-Metrics': includeMetrics.toString()
      }
    });

  } catch (error) {
    logger.error('Erro durante exportação de assistentes', { 
      userId: session.user.id, 
      error: error instanceof Error ? error.message : String(error) 
    });
    return NextResponse.json(
      { error: 'Erro interno durante exportação' }, 
      { status: 500 }
    );
  }
}