"""add user_integrations table

Revision ID: 581c17f50ab8
Revises: 0001_init
Create Date: 2026-03-02 20:53:32.196748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '581c17f50ab8'
down_revision: Union[str, None] = '0001_init'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_integrations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('integration_type', sa.String(length=50), nullable=False, comment='Integration type: instagram, chatwit'),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True, comment='Fernet-encrypted OAuth access token'),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_user_id', sa.String(length=100), nullable=True, comment='User ID on the external platform'),
    sa.Column('external_username', sa.String(length=100), nullable=True),
    sa.Column('external_profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'integration_type', name='uq_user_integrations_tenant_user_type')
    )
    op.create_index(op.f('ix_user_integrations_tenant_id'), 'user_integrations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_integrations_user_id'), 'user_integrations', ['user_id'], unique=False)
    op.alter_column('ai_conversations', 'conversation_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type of conversation (triagem, investigacao, redacao, etc.)',
               existing_comment='Type of conversation',
               existing_nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment='Action performed (create, update, delete, etc.)',
               existing_comment='Action performed',
               existing_nullable=False)
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Previous values before change',
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='New values after change',
               existing_nullable=True)
    op.alter_column('automations', 'trigger_conditions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Conditions that must be met to trigger',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('automations', 'actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Array of actions to execute',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('automations', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional automation metadata',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('briefings', 'urgent_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Urgent cases requiring immediate attention',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('briefings', 'attention_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Cases requiring attention',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('briefings', 'good_news_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Positive updates',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('briefings', 'noise_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Low-priority updates',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('briefings', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional briefing metadata (stats, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('client_notes', 'mentions',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='List of mentioned user IDs',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Event payload data',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('legal_cases', 'cnj_number',
               existing_type=sa.VARCHAR(length=25),
               comment='CNJ process number (NNNNNNN-DD.AAAA.J.TR.OOOO)',
               existing_comment='CNJ process number',
               existing_nullable=False)
    op.alter_column('legal_cases', 'custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Custom fields for tenant-specific data',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('peticao_documentos', 'sigiloso',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Documento marcado como sigiloso pelo usuário',
               existing_nullable=False)
    op.alter_column('tenants', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Tenant-specific settings and preferences',
               existing_comment='Tenant-specific settings',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('timeline_events', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Type of event (message_received, movement_detected, etc.)',
               existing_comment='Type of event',
               existing_nullable=False)
    op.alter_column('timeline_events', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional event data',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('user_preferences', 'preference_key',
               existing_type=sa.VARCHAR(length=100),
               comment="Preference key (e.g., 'dashboard_filters', 'theme')",
               existing_nullable=False)
    op.alter_column('user_preferences', 'preference_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Preference value as JSON',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('worker_schedules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker_schedules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('user_preferences', 'preference_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Preference value as JSON',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('user_preferences', 'preference_key',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Preference key (e.g., 'dashboard_filters', 'theme')",
               existing_nullable=False)
    op.alter_column('timeline_events', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional event data',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('timeline_events', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Type of event',
               existing_comment='Type of event (message_received, movement_detected, etc.)',
               existing_nullable=False)
    op.alter_column('tenants', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Tenant-specific settings',
               existing_comment='Tenant-specific settings and preferences',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('peticao_documentos', 'sigiloso',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Documento marcado como sigiloso pelo usuário',
               existing_nullable=False)
    op.alter_column('legal_cases', 'custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Custom fields for tenant-specific data',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('legal_cases', 'cnj_number',
               existing_type=sa.VARCHAR(length=25),
               comment='CNJ process number',
               existing_comment='CNJ process number (NNNNNNN-DD.AAAA.J.TR.OOOO)',
               existing_nullable=False)
    op.alter_column('events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Event payload data',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('client_notes', 'mentions',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='List of mentioned user IDs',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('briefings', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional briefing metadata (stats, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('briefings', 'noise_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Low-priority updates',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('briefings', 'good_news_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Positive updates',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('briefings', 'attention_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Cases requiring attention',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('briefings', 'urgent_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Urgent cases requiring immediate attention',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('automations', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional automation metadata',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('automations', 'actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Array of actions to execute',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('automations', 'trigger_conditions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Conditions that must be met to trigger',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='New values after change',
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Previous values before change',
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment='Action performed',
               existing_comment='Action performed (create, update, delete, etc.)',
               existing_nullable=False)
    op.alter_column('ai_conversations', 'conversation_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type of conversation',
               existing_comment='Type of conversation (triagem, investigacao, redacao, etc.)',
               existing_nullable=False)
    op.drop_index(op.f('ix_user_integrations_user_id'), table_name='user_integrations')
    op.drop_index(op.f('ix_user_integrations_tenant_id'), table_name='user_integrations')
    op.drop_table('user_integrations')
    # ### end Alembic commands ###
