"""add_totp_secret_to_certificado_digital

Revision ID: 68a38600a6bc
Revises: 92e1e10bd120
Create Date: 2026-03-03 12:25:51.711373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a38600a6bc'
down_revision: Union[str, None] = '92e1e10bd120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificados_digitais', sa.Column('totp_secret_encrypted', sa.LargeBinary(), nullable=True, comment='Fernet-encrypted TOTP secret (base32) for PJe SSO 2FA'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificados_digitais', 'totp_secret_encrypted')
    # ### end Alembic commands ###
