/**
 * Queue Management Constants
 */

export const QUEUE_CONSTANTS = {
	DEFAULT_RETRY_ATTEMPTS: 3,
	DEFAULT_RETRY_DELAY: 5000,
	MAX_JOB_TIMEOUT: 300000, // 5 minutes
	DEFAULT_CONCURRENCY: 10,
	MAX_CONCURRENCY: 50,
	CLEANUP_INTERVAL: 60000, // 1 minute
	METRICS_INTERVAL: 30000, // 30 seconds
} as const;

export const ERROR_CODES = {
	QUEUE_NOT_FOUND: "QUEUE_NOT_FOUND",
	JOB_NOT_FOUND: "JOB_NOT_FOUND",
	INVALID_JOB_DATA: "INVALID_JOB_DATA",
	QUEUE_ALREADY_EXISTS: "QUEUE_ALREADY_EXISTS",
	PERMISSION_DENIED: "PERMISSION_DENIED",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	SYSTEM_ERROR: "SYSTEM_ERROR",
} as const;

export const STATUS_CODES = {
	SUCCESS: 200,
	CREATED: 201,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	INTERNAL_SERVER_ERROR: 500,
} as const;
